# Generated by Django 5.1.2 on 2024-11-09 23:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0007_article_course_challenge_course_documentation_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='challenge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cms.challenge'),
        ),
    ]
