# Generated by Django 5.1.2 on 2024-11-11 11:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0008_submission_challenge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='date_time',
            field=models.DateTimeField(blank=True, help_text='Date and time of the workshop', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='Instructor responsible for the course', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_instructed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='meeting_link',
            field=models.URLField(blank=True, help_text='URL for the workshop meeting (e.g., Zoom link)', null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50),
        ),
        migrations.AlterField(
            model_name='video',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=50),
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('meeting_link', models.URLField(help_text='URL for the workshop meeting (e.g., Zoom link)')),
                ('date_time', models.DateTimeField(help_text='Date and time of the workshop')),
                ('duration', models.DurationField(help_text='Duration of the workshop (e.g., 2 hours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(to='cms.category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='cms.course')),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor responsible for the workshop', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workshops_instructed', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='cms.tag')),
            ],
            options={
                'ordering': ['date_time'],
            },
        ),
    ]
