# Generated by Django 5.1.2 on 2024-11-11 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0009_course_date_time_course_instructor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a picture for the course', null=True, upload_to='course_pics/'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='picture',
            field=models.ImageField(blank=True, help_text='Upload a picture for the workshop', null=True, upload_to='workshop_pics/'),
        ),
    ]
