# Generated by Django 5.1.2 on 2024-11-11 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0010_course_picture_workshop_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='picture',
            field=models.ImageField(blank=True, help_text='Image for the course', null=True, upload_to='course_pics/'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='picture',
            field=models.ImageField(blank=True, help_text='Image for the workshop', null=True, upload_to='workshop_pics/'),
        ),
    ]
