# Generated by Django 5.1.2 on 2024-11-11 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0012_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='workshop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='cms.workshop'),
        ),
    ]
