# Generated by Django 5.1.2 on 2024-11-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0013_submission_workshop'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='points_cost',
            field=models.PositiveIntegerField(default=25, help_text='Points required to attend the workshop'),
        ),
    ]
