# Generated by Django 5.1.2 on 2024-11-11 13:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0014_workshop_points_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for reading the article'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for completing the assignment'),
        ),
        migrations.AddField(
            model_name='course',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for completing the course'),
        ),
        migrations.AddField(
            model_name='documentation',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for reading the documentation'),
        ),
        migrations.AddField(
            model_name='post',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for reading the post'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for completing the quiz'),
        ),
        migrations.AddField(
            model_name='submission',
            name='points_awarded',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for this submission'),
        ),
        migrations.AddField(
            model_name='video',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for watching the video'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='points',
            field=models.PositiveIntegerField(default=0, help_text='Points awarded for attending the workshop'),
        ),
        migrations.CreateModel(
            name='ArticleRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Points awarded for reading the article')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='cms.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'article')},
            },
        ),
        migrations.CreateModel(
            name='DocumentationRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(auto_now_add=True)),
                ('points_awarded', models.PositiveIntegerField(default=0, help_text='Points awarded for reading the documentation')),
                ('documentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reads', to='cms.documentation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentations_read', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'documentation')},
            },
        ),
    ]
