# Generated by Django 5.1.2 on 2024-11-11 13:54

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0015_article_points_assignment_points_course_points_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='timelineevent',
            unique_together={('user', 'event_type', 'content_type', 'object_id')},
        ),
    ]
