# Generated by Django 5.1.2 on 2024-11-11 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0016_alter_timelineevent_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('course', 'Course Meeting'), ('assignment', 'Assignment Deadline'), ('quiz', 'Quiz Deadline'), ('workshop', 'Workshop Meeting'), ('challenge', 'Challenge Deadline')], max_length=50),
        ),
    ]
