# Generated by Django 5.1.2 on 2024-11-11 14:06

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0017_alter_timelineevent_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(default=timezone.now),
        ),
        migrations.AddField(
            model_name='challenge',
            name='due_date',
            field=models.DateTimeField(default=timezone.now),
        ),
    ]
