# Generated by Django 5.1.2 on 2024-11-11 14:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0018_challenge_due_date_quiz_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='cms.course'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cms.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
