# Generated by Django 5.1.2 on 2024-11-11 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0019_alter_challenge_course_alter_challenge_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='challenges', to='cms.course'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='cms.course'),
        ),
    ]
