# Generated by Django 5.1.2 on 2024-11-11 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_alter_challenge_course_alter_quiz_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('course', 'Course Meeting'), ('assignment', 'Assignment Deadline'), ('quiz', 'Quiz Deadline'), ('workshop', 'Workshop Meeting'), ('challenge_start', 'Challenge Start'), ('challenge_deadline', 'Challenge Deadline')], max_length=50),
        ),
    ]
