# Generated by Django 5.1.2 on 2024-11-11 16:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0021_alter_timelineevent_event_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='course',
            name='meeting_link',
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('meeting_link', models.URLField(blank=True, help_text='URL for the session meeting (e.g., Zoom link)', null=True)),
                ('date_time', models.DateTimeField(blank=True, help_text='Date and time of the session', null=True)),
                ('content', models.TextField(help_text='Content or description of the session')),
                ('points', models.PositiveIntegerField(default=0, help_text='Points awarded for attending the session')),
                ('categories', models.ManyToManyField(to='cms.category')),
                ('course', models.ForeignKey(help_text='The course that this session belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='cms.course')),
                ('instructor', models.ForeignKey(blank=True, help_text='Instructor responsible for the session', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions_instructed', to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='cms.tag')),
            ],
        ),
    ]
