# Generated by Django 5.1.2 on 2024-11-11 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_remove_course_date_time_remove_course_meeting_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='link',
            field=models.URLField(blank=True, help_text='URL to access or submit the assignment form', null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='link',
            field=models.URLField(blank=True, help_text='URL to access or submit the quiz form', null=True),
        ),
    ]
