# Generated by Django 5.1.2 on 2024-11-11 20:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0025_alter_submission_unique_together_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'content_type', 'object_id')},
        ),
    ]
