# Generated by Django 5.1.2 on 2024-11-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0026_alter_submission_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='picture',
            field=models.ImageField(blank=True, help_text='Image for the course', null=True, upload_to='challenge_pics/'),
        ),
    ]
