# Generated by Django 5.1.2 on 2024-11-12 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0027_challenge_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='proficiency_level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='timelineevent',
            name='event_type',
            field=models.CharField(choices=[('course', 'Course Meeting'), ('session', 'Session Meeting'), ('assignment', 'Assignment Deadline'), ('quiz', 'Quiz Deadline'), ('workshop', 'Workshop Meeting'), ('challenge_start', 'Challenge Start'), ('challenge_deadline', 'Challenge Deadline')], max_length=50),
        ),
    ]
