# Generated by Django 5.1.2 on 2024-11-12 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0028_course_proficiency_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='duration',
            field=models.DurationField(default=60, help_text='Duration of the workshop (e.g., 2 hours)'),
        ),
    ]
