# Generated by Django 5.1.2 on 2024-11-16 23:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='user',
            field=models.ManyToManyField(blank=True, help_text='Users who can use this coupon. Leave blank for all users.', to=settings.AUTH_USER_MODEL),
        ),
    ]
