# Generated by Django 5.1.2 on 2024-11-17 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0029_alter_workshop_duration'),
        ('products', '0007_product_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='products', to='cms.course'),
        ),
    ]
