# Generated by Django 5.1.2 on 2024-11-19 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_alter_payment_id_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('vcash', 'VodafoneCash'), ('instapay', 'InstaPay')], max_length=50),
        ),
    ]
