# Generated by Django 5.1.2 on 2024-11-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_paymentorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('vcash', 'VodafoneCash'), ('instapay', 'InstaPay')], max_length=50),
        ),
        migrations.AlterField(
            model_name='paymentorder',
            name='gateway',
            field=models.CharField(choices=[('vcash', 'VodafoneCash'), ('instapay', 'InstaPay')], max_length=20),
        ),
    ]
