# Generated by Django 5.1.2 on 2024-11-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_alter_payment_gateway_alter_paymentorder_gateway'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='gateway',
            field=models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal')], max_length=50),
        ),
        migrations.DeleteModel(
            name='PaymentOrder',
        ),
    ]
